#!/bin/sh

PLAYGROUNDS_DIR="/tmp/cabal-playgrounds"
TIMESTAMP=$(date +"%Y-%m-%d-%H:%M:%S")
PROJECT_NAME="playground-${TIMESTAMP}"
PROJECT_DIR="${PLAYGROUNDS_DIR}/${PROJECT_NAME}"

mkdir -p $PROJECT_DIR
cd $PROJECT_DIR

pkgflags=""
for pkg in $@ ; do
  pkgflags="${pkgflags} -d ${pkg}"
done

cabal init --exe -p tmp --version 0.1 -n -q -x tmp.cabal --application-dir . -m -d base $pkgflags
cabal-fmt --inplace tmp.cabal
echo "Successfully created cabal project in $PROJECT_DIR"
code $PROJECT_DIR 
