#!/bin/sh

PLAYGROUNDS_DIR="/tmp/cabal-playgrounds"
TIMESTAMP=$(date +"%Y%m%d%H%M%S")
PROJECT_NAME="playground${TIMESTAMP}"
PROJECT_DIR="${PLAYGROUNDS_DIR}/${PROJECT_NAME}"

mkdir -p $PROJECT_DIR
cd $PROJECT_DIR

pkgflags=""
for pkg in $@ ; do
  pkgflags="${pkgflags} -d ${pkg}"
done

cabal init --libandexe -d base $pkgflags
$EDITOR  $PROJECT_DIR
